version: "3.8"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    networks:
      - mysql

  nestjs-api:
    image: applifting_full_stack_exercise
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: api
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - mysql
    depends_on:
      - mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://host.docker.internal:3000/health -f || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 0s

  nextjs-fe:
    image: applifting_full_stack_exercise_fe
    volumes:
      - ./fe:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: fe
      args:
        - API_ENDPOINT_GRAPHQL_CODEGEN=${API_ENDPOINT_GRAPHQL_CODEGEN}
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - mysql
    depends_on:
      nestjs-api:
        condition: service_healthy

networks:
  mysql:
    driver: bridge
