version: "3"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    networks:
      - mysql

  nestjs-api:
    image: applifting_full_stack_exercise
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: api
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - mysql
    depends_on:
      - mysql

networks:
  mysql:
    driver: bridge

# volumes:
#   nestjs-api:
#     external: false
