module.exports = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    darkMode: 'media', // or 'media' or 'class'
    theme: {
        screens: {
            'mobile-landscape': '36rem',
            tablet: '48rem',
            'tablet-landscape': '68.5rem',
            desktop: '80rem',
            'large-desktop': '90rem',
            fullhd: '120rem',
        },
        extend: {
            borderRadius: {
                xl: '0.625rem',
            },
            colors: {
                lighterGrey: '#6C757D',
                lightGrey: '#F8F9FA',
                darkGrey: '#212529',
                grey: '#DFDFDF',
                blue: '#007BFF',
                red: '#E2021D',
            },
            gridColumnEnd: {
                13: '13',
                14: '14',
                15: '15',
                16: '16',
                17: '17',
            },
            height: {
                '56.25vw': '56.25vw',
                2.5: '0.625rem',
                3.5: '0.875rem',
                5: '1.25rem',
                5.5: '1.375rem',
                9.25: '2.3125rem',
            },
            margin: {
                0.25: '0.0625rem',
                0.5: '0.125rem',
                15: '3.75rem',
            },
            maxHeight: {
                '16-9': '56.25vw',
            },
            maxWidth: {
                120: '30rem',
                256: '64rem',
                306: '76.5rem',
            },
            padding: {
                '16/9': '56.25%',
                5.5: '22px',
                6.5: '1.625rem',
                7.5: '1.875rem',
                15: '3.75rem',
                27: '6.75rem',
            },
            transitionProperty: {
                width: 'width',
                'transform-color': 'transform, color',
                'background-shadow': 'background, box-shadow',
                'transform-opacity': 'transform, opacity',
                'visibility-opacity': 'visibility, opacity',
                'max-height': 'max-height',
                'transform-opacity-visibility': 'transform, opacity, visibility',
                'transform-background-padding': 'transform, background, padding',
                'color-opacity': 'color, opacity',
                'transform-shadow': 'transform, box-shadow',
                'max-height-z-index-background': 'max-height, z-index, background',
                'z-index': 'z-index',
            },
            transitionDuration: {
                fadeIn: '1000ms',
            },
            width: {
                2.5: '0.625rem',
                3.5: '0.875rem',
                5: '1.25rem',
                5.5: '1.375rem',
                42.5: '10.625rem',
                56.75: '14.1875rem',
            },
            zIndex: {
                1: '1',
                2: '2',
                3: '3',
                4: '4',
                9997: '9997',
                9998: '9998',
                9999: '9999',
            },
            fontSize: {
                sm: ['15px', '22.5px'],
                p: '1.25rem',
                '3xl': ['2rem', '2.6rem'],
                xl: ['1.5rem', '1.75rem'],
                xxs: ['0.875rem', '1.25rem'],
                xxxs: ['0.813rem', '1.138rem'],
                xxxxs: ['0.875rem', '1.25rem'],
                xl: ['1.25rem', '1.625rem'],
                15: '0.9375rem',
                14: ['0.875rem', '1.3125rem'],
                13: '0.8125rem',
                14: ['2.5rem', '3rem'],
            },
            lineHeight: {
                1.5: '1.5',
                8.5: '2.125rem',
                11: '3rem',
            },
            translate: {
                0.1375: '0.55rem',
            },
            boxShadow: {
                contact: '0px 5px 25px 0px rgba(0, 0, 0, 0.1)',
                sliderBtn: '0px 10px 20px 0px rgba(0, 0, 0, 0.08)',
                referenceCard: '0px 20px 40px 0px rgba(0,0,0,0.07)',
                form: '0px 10px 50px 0px rgba(0,0,0,0.1)',
                userStatistic: '0px 10px 40px rgba(0,0,0,0.08)',
                redCard: '0px 20px 20px 0px rgba(241, 29, 55, 0.15)',
                greenCard: '0px 20px 20px 0px rgba(6, 172, 155, 0.15)',
                blueCard: '0px 20px 20px 0px rgba(54, 117, 240, 0.15)',
            },
        },
    },
    variants: {
        extend: {},
    },
};
